# Generated by Django 4.2.7 on 2024-01-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('c_password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
